### ISSUE TITLE
submit new not working

### ISSUE THREAD

**Issue by hasmaneuroda** [mwarning/chaos-sticker-collection#13]
Trying to submit a new sticker via https://mwarning.github.io/chaos-sticker-collection/submit.html

When clicking the submit-button on the mentioned page, a java popup appears saying "Error:" and nothing else happens.
Therefore I'm not able to submit anything.

**Comment by mwarning** [comment]
Ah right, sorry. The button is broken because I have to always copy the https certificate and restart the webserver for that.
I will replace it with something else. Please feel free to submit images by email to me, or as a pull request, issue ticket - whatever works for you.

**Comment by hasmaneuroda** [comment]
Okay, I'll do that. Thanks!

**Comment by hasmaneuroda** [comment]
Thank you very much!
