### ISSUE TITLE
Add sticker thing doesn't work for me

### ISSUE THREAD

**Issue by MikeTango** [mwarning/chaos-sticker-collection#15]
Hi, 

want to drop these, all https://creativecommons.org/licenses/by-nc-sa/4.0/ by me (miketango@miketango.de)
![victimblaming_fullsize](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/4de18d8f-fa8e-425a-90ca-07d9ee08d942)

this should come out at 300dpi and original truck size for your own truck which does not go to france

![01_bknsince](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/0e7c42f2-87d6-45da-bed8-3d972a4cb9b8)
![02_scrapheap](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/71d9ed96-9080-46c8-8a98-2280d63eebd4)
![03_fuckup](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/ae23603b-b37b-4d50-a046-1201c4a2757d)
![aluhut1](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/50fc6751-9f52-4b3a-9c6b-2efedd95644e)
![bandlc_print](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/5caf373c-5634-4a41-912a-6822fae90067)
![buydlc jpg](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/7aa9a722-775a-4e62-b43f-352ad82bcd6d)
![cybercrew_OG](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/50f21a81-a76d-479c-b08b-564c4df1526a)
![cybercyber_01](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/ad56ba16-3864-4d18-a9c1-0b5209a01c56)
![cybercyber_reverse](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/54b474a7-fcb4-4708-bb5e-35e9430cfe8d)
![Dauerleihgabe](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/3da3cdd7-c60a-4d63-8585-db27d3a5cbcc)
![Fluor](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/dc152ac2-c39d-4411-bc94-7cce348fbb86)
![Mängelexemplar](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/4dd0d1c4-2325-448d-9a2f-cfd9a5e459dd)

**Comment by MikeTango** [comment]
[CCU1.pdf](https://github.com/mwarning/chaos-sticker-collection/files/13792870/CCU1.pdf)
![cybercrew](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/623698b4-0bad-48fc-85d2-780bd94dee87)
![cybercrew_blk](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/28ae57d0-cce4-4825-8106-dd4abf131dc6)
![cybercrew_mirroR](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/26363249-2015-478f-bc1d-05f7ee305231)
![acw](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/465c5684-1a6d-46a6-ac1a-737a5b3c203d)
![acw](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/5721ef85-8fed-4f29-91d5-d2a22e851ac4)


also all https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by mwarning** [comment]
Thank you very much. :-)
I have added the stickers. Are the ones from the last post also from you ("Cyber - Cyber" and "All Creatures Welcome")?
Just so that get the attribution correct. :-)

**Comment by MikeTango** [comment]
[aluhut.pdf](https://github.com/mwarning/chaos-sticker-collection/files/13795438/aluhut.pdf)
[Dauerleihgabe.pdf](https://github.com/mwarning/chaos-sticker-collection/files/13795439/Dauerleihgabe.pdf)
[klagtnicht.pdf](https://github.com/mwarning/chaos-sticker-collection/files/13795440/klagtnicht.pdf)
[Mängelexemplar.pdf](https://github.com/mwarning/chaos-sticker-collection/files/13795441/Mangelexemplar.pdf)
[mileinsatz.pdf](https://github.com/mwarning/chaos-sticker-collection/files/13795442/mileinsatz.pdf)
![mileinsatz](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/960872a8-91bc-447c-bb36-f7cf6fd4b7eb)
[miluse.pdf](https://github.com/mwarning/chaos-sticker-collection/files/13795443/miluse.pdf)
![miluse](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/c184d487-c8dc-41b6-a7af-2076fbebac99)

die hier noch...gleiche Lizenz

**Comment by MikeTango** [comment]
![Akkuflex_hilti_print](https://github.com/mwarning/chaos-sticker-collection/assets/3368005/33ca67ad-ebaa-4a33-beb0-cd913bdd07b7)

und das...soweit man das geklaute Zeug lizensieren kann

**Comment by mwarning** [comment]
Btw., hast du die Vorlage von dem hier? https://mwarning.github.io/chaos-sticker-collection/images/alle-gut-hackbar/alle-gut-hackbar.png
