### ISSUE TITLE
Pridetopia

### ISSUE THREAD

**Issue by jdreichmann** [mwarning/chaos-sticker-collection#17]
So far, the following Pridetopia stickers have been printed:

https://entropia.de/Datei:Pridetropia.svg as "normal" 50x70mm Sticker on white background, rectangular.
Rights not declared in wiki, probably all to @madonius?

https://entropia.de/Datei:Transtropia.svg
https://entropia.de/Datei:Lesbtropia_white_stripe.svg
https://entropia.de/Datei:Nonbinarytropia.svg
Printed in teebeutel shape (custom cutout) as "small" 35x47mm Stickers, all source files public domain, the adjustments for the print done by Clemens from Entropia. All rights declared in linked Wiki.

Raw files uploaded to wirmachendruck attached incl. Cutout Layer
[Lesbian-2.pdf](https://github.com/mwarning/chaos-sticker-collection/files/13801080/Lesbian-2.pdf)
[NonBinary-final_echt_v2.pdf](https://github.com/mwarning/chaos-sticker-collection/files/13801082/NonBinary-final_echt_v2.pdf)
[Traaaans.pdf](https://github.com/mwarning/chaos-sticker-collection/files/13801083/Traaaans.pdf)

**Comment by mwarning** [comment]
The stickers were added - thank you!
