### ISSUE TITLE
Backlink to repository

### ISSUE THREAD

**Issue by rugk** [mwarning/chaos-sticker-collection#19]
A link to the repository would be great (and preferably not at the end of the page, I should not have to scroll until the end), so contributors can easily find their way to add new stickers.

The link could just be a "contribute" link or so.

**Comment by mwarning** [comment]
The "Submit New" link was added back again and now links to the repository.

**Comment by rugk** [comment]
Oh yeah sorry totally missed that. Apparently I expected some GitHub logo or source link or so. But I guess it's kinda fine🫣

**Comment by mwarning** [comment]
I have added a github logo. What do you think?

**Comment by rugk** [comment]
You mean you've replaced the text with a GitHub logo. Yeah that is quite clear now, IMHO!

Just at least on desktops, I would be fine/it would maybe be actually still as good or even better to keep the old text _in addition_ to it. Aka: "[github logo] Submit new". On desktop screens there is plenty of place to add that text…

**Comment by mwarning** [comment]
added - I do not have a strong opinion here :)

**Comment by rugk** [comment]
Good on desktop but can you hide the text onsmakler screens? (Just a media query should fix it)

After all, on mobile it now takes two lines.

![Screenshot_20240107-212138_1](https://github.com/mwarning/chaos-sticker-collection/assets/11966684/0a6b26dd-59f6-40fc-be84-f10e3120b7a1)

**Comment by mwarning** [comment]
Oh, I see.
@rugk could you make a MR? I have my share of troubles with mobile detection..

**Comment by rugk** [comment]
Sure, did that. Next time maybe link commits like https://github.com/mwarning/chaos-sticker-collection/commit/494fa995b733b3587960db2e61bcced1bae63c9a to the issues you fix (just include a link or the #number in the description), as I was just looking for how you did and what you did.
