### ISSUE TITLE
sticker resources to import

### ISSUE THREAD

**Issue by mwarning** [mwarning/chaos-sticker-collection#2]
- <strike>https://maryshi.ro/</strike> - done
- <strike>https://github.com/rixx/sticker</strike> - done
- <strike>https://github.com/irimi1/cyberwehr-aufkleber</strike> - done
- <strike>https://github.com/SFTtech/sticker</strike> - done
- <strike>https://github.com/rstudio/hex-stickers</strike> - done
- <strike>https://github.com/rstudio/hex-stickers/</strike> - done
- https://github.com/securingdev/awesome-stickers (segmentation: https://github.com/securingdev/awesome-stickers/issues/12)
- <strike>https://thestickerarchive.tumblr.com/</strike> - done
- https://github.com/rubo77/freifunk-sticker
- https://fsfe.org/contribute/spreadtheword.en.html
- add all GPN logos as sticker?

**Comment by mwarning** [comment]
T-Shirts: https://gitlab.com/XenGi/c_neidi-files/-/tree/master (MIT)

**Comment by mwarning** [comment]
https://github.com/irimi1/cyberwehr-aufkleber

**Comment by mwarning** [comment]
@irimi1 mayb I add your cyberwehr images? And what license to you prefer? (CC0-1.0?)

**Comment by mwarning** [comment]
https://github.com/rixx/sticker

**Comment by mwarning** [comment]
https://github.com/SFTtech/sticker

**Comment by irimi1** [comment]
> @irimi1 may I add your cyberwehr images? And what license to you prefer? (CC0-1.0?)

Yes please do, I don’t think the "Unlicense" (basically public domain) conflicts with CC0, so it should be fine.
You can also what I keep at https://git.sr.ht/~irimi1/stickers :)

I think I’ll use this opportunity to make a public domain compatible version of my "tuwat" sticker (with an open font): https://irimi.one/stickers/labernich/
I’ll let you know when I’m done :)

**Comment by mwarning** [comment]
@irimi1 Awesome! I will add it later.

"Unlicense" is fine.

**Comment by irimi1** [comment]
I added most of my designs already. Not all of them are “nerd stickers” though, feel free to choose yourself :)

**Comment by irimi1** [comment]
My alias includes the 1 btw ;)

**Comment by mwarning** [comment]
@irimi1 sorry about that. I will correct it.

**Comment by irimi1** [comment]
@mwarning no worries, thanks <3
