### ISSUE TITLE
Cross side beim einreichen von neuen Stickern

### ISSUE THREAD

**Issue by SebiPanther** [mwarning/chaos-sticker-collection#9]
Hallo,
ich wollte neue Sticker einreichen, bekomme aber folgenden Fehler:

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://mwarning.de:4223/submit. (Grund: CORS-Anfrage schlug fehl).

Das Javaskript meldet einfach nur einen "Error".

Wird daran liegen, das JavaSkript von https://mwarning.github.io/chaos-sticker-collection/submit.html auf https://mwarning.de:4223/submit zugreifen will. Um das zu ermöglichen muss mwarning.de:4223 das per CORS zulassen über ein paar Response-Header-Optionen: https://de.wikipedia.org/wiki/Cross-Origin_Resource_Sharing

Wäre super nett, wenn du das beheben würdest. Vielen dank!

Grüße Sebi

**Comment by mwarning** [comment]
Hi Sebi,

vielen lieben Dank! Ich schaue später mal das ich das aktiviere.

**Comment by mwarning** [comment]
CORS headers habe ich gesetzt. Aber das funktioniert irgenswie noch nicht: https://github.com/mwarning/chaos-sticker-collection/blob/master/submit-server.py#L125

**Comment by SebiPanther** [comment]
Hallo @mwarning,
danke für deine Mühe!
Wenn ich nun versuche neue Sticker ein zu reichen, dann bekomme ich die Meldung "Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://mwarning.de:4223/submit. Grund wird das hier sein: https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy
Dein Programm greift von https://mwarning.github.io/chaos-sticker-collection/submit.html auf https://mwarning.de:4223/submit (Abgelaufenes Zertifikat btw.). Also anderer Host und anderer Port.
Ich würde zum testen folgendes machen
1) Zertifikat erneuern
2) https://github.com/mwarning/chaos-sticker-collection/blob/master/submit-server.py#L124 Zeile 124 ändern in: self.send_header('Access-Control-Allow-Credentials', 'false')
3) https://github.com/mwarning/chaos-sticker-collection/blob/master/submit-server.py#L127 Zeile 127 ändern in: self.send_header("Access-Control-Allow-Headers", "*")
4) Wenn das klappt https://github.com/mwarning/chaos-sticker-collection/blob/master/submit-server.py#L125 Zeile 125 ändern in: self.send_header('Access-Control-Allow-Origin', 'https://mwarning.github.io')
Ich hoffe es klappt!
Grüße Sebi

**Comment by mwarning** [comment]
hi Sebi,

ich habe mal versucht auf dem server ein update durchzuführen für den certbot... und anscheinend kommt der server gerade nicht hoch. :-]
Wenn die Maschine wieder läuft probiere ich es aus!

**Comment by mwarning** [comment]
Du kannst mal testen ob es jetzt für dich geht.

**Comment by SebiPanther** [comment]
Schlägt immer noch fehl, wenn man nicht das abgelaufene Zertifikat nicht vorher explizit erlaubt, in dem man vorher auf https://mwarning.de:4223/submit geht und seinem Browser diese Ausnahme beibringt.
Wäre echt nett, wenn du noch das Zertifikat aktualisierst. Benutzer kriegen sonst keine sinnvolle Meldung, warum es gerade nicht geht.
Vielen dank!

**Comment by mwarning** [comment]
ok, Zertifikat ist jetzt erneuert. Ein Test hat bei mir geklappt.

**Comment by mwarning** [comment]
I see a few submissions and upload them later. Thank you for your help! :-)
